#!/bin/sh
# bootstrap: install dependencies

if ! command -v hugo; then
        echo "\`hugo\` could not be found, is it installed? Try following https://gohugo.io/getting-started/installing/" >&2
        exit 1
else
        echo "\`hugo\`: found!"
fi

echo "initializing submodules"

git submodule update

echo "Everything is ready! Try it out by running \`scripts/run\`"
